from setuptools import setup

setup(name='car',
      version='0.1',
      author='Krzysztof Adamkiewicz',
      author_email='24498@edu.p.lodz.pl',
      description='Package for controlling jetracer car.',
      long_description="",
      packages=['car'],
      classifiers=['Development Status :: 3 - Alpha',
                   'Intended Audience :: Science/Research',
                   'Natural Language :: English',
                   'Operating System :: OS Independent',
                   'Programming Language :: Python :: 2.7',
                   'Programming Language :: Python :: 3',
                   'Programming Language :: Python :: 3.2',
                   'Programming Language :: Python :: 3.3',
                   'Programming Language :: Python :: 3.4',
                   'Programming Language :: Python :: 3.5',
                   'Programming Language :: Python :: 3.6',
                  ],
     )